# Generated by Django 5.0.4 on 2024-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_sent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=10),
        ),
    ]
