# Generated by Django 5.0.4 on 2024-04-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_alter_transaction_amount_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='payapp.transaction'),
        ),
    ]
