# Generated by Django 5.0.4 on 2024-04-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], max_length=10),
        ),
    ]
